/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#747878",
        "inverse-primary": "#c6c6c7",
        "on-primary-container": "#747676",
        "surface-variant": "#e5e2e1",
        "primary": "#5d5f5f",
        "tertiary-fixed-dim": "#c9c6c5",
        "surface-container-high": "#ebe7e7",
        "surface": "#fcf8f8",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ffffff",
        "tertiary-fixed": "#e5e2e1",
        "secondary-container": "#fccc38",
        "inverse-on-surface": "#f4f0ef",
        "surface-container": "#f1edec",
        "inverse-surface": "#313030",
        "tertiary": "#5f5e5e",
        "error-container": "#ffdad6",
        "primary-container": "#ffffff",
        "on-primary-fixed": "#1a1c1c",
        "surface-bright": "#fcf8f8",
        "surface-container-highest": "#e5e2e1",
        "on-tertiary-fixed": "#1c1b1b",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#777575",
        "on-surface-variant": "#444748",
        "outline-variant": "#c4c7c8",
        "on-secondary-fixed": "#241a00",
        "on-error-container": "#93000a",
        "surface-dim": "#ddd9d9",
        "on-primary-fixed-variant": "#454747",
        "primary-fixed-dim": "#c6c6c7",
        "on-secondary-container": "#6f5600",
        "surface-container-lowest": "#ffffff",
        "background": "#fcf8f8",
        "on-tertiary-fixed-variant": "#474646",
        "secondary-fixed": "#ffdf90",
        "on-secondary-fixed-variant": "#584400",
        "surface-tint": "#5d5f5f",
        "surface-container-low": "#f6f3f2",
        "secondary": "#755b00",
        "primary-fixed": "#e2e2e2",
        "on-error": "#ffffff",
        "on-background": "#1c1b1b",
        "secondary-fixed-dim": "#f0c12c",
        "on-surface": "#1c1b1b",
        "on-primary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "sm": "12px",
        "md": "24px",
        "gutter": "24px",
        "lg": "48px",
        "xs": "4px",
        "xl": "80px",
        "container-max": "1280px",
        "base": "8px"
      },
      fontFamily: {
        "h3": ["Epilogue"],
        "h1": ["Epilogue"],
        "h2": ["Epilogue"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-bold": ["Plus Jakarta Sans"],
        "display": ["Epilogue"],
        "body-md": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "h3": ["20px", {"lineHeight": "1.4", "fontWeight": "700"}],
        "h1": ["36px", {"lineHeight": "1.2", "fontWeight": "800"}],
        "h2": ["28px", {"lineHeight": "1.3", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-bold": ["14px", {"lineHeight": "1.4", "fontWeight": "700"}],
        "display": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
